#services:

#  photo_service:
#    class: App\Services\PhotoService
#    arguments:
#      - 'argument_1'
#      - 'argument_2'
#  product_controller:
#    class: App\Controllers\ProductController
#    arguments:
#      - '@photo_service'
#  twig:
#    class: Twig\Environment
#    arguments: [ '@twig.loader.filesystem', { debug: true } ]
#    calls:
#      - [ 'addGlobal', [ 'app_name', 'My App' ] ]
#      - [ 'addGlobal', [ 'base_url', '/' ] ]
#    tags: [ { name: 'container.service_subscriber' } ]
#  twig.loader.filesystem:
#    class: Twig\Loader\FilesystemLoader
#    arguments:
#      $paths:
#        - '%kernel.project_dir%/Views'
